[db]
username = "username"
password = "password"
db_name = "flare_xrp_indexer"
port = 5432
drop_table_at_start = false

[indexer]
confirmations = 0
max_block_range = 100
max_concurrency = 10
start_block_number = 780000

[blockchain]
url = "https://s.altnet.rippletest.net:51234"

[timeout]
timeout_millis = 3000

[logger]
level = "DEBUG"
file = "logs/xrp_indexer.log"
console = true
