[db]
username = "username" # can be specified with env DB_USERNAME
password = "password" # can be specified with env DB_PASSWORD
db_name = "flare_xrp_indexer"
port = 5432
drop_table_at_start = false
history_drop = 3600
history_drop_frequency = 600

[indexer]
confirmations = 1
max_block_range = 100
max_concurrency = 10
start_block_number = 780000

[blockchain]
url = "https://s.altnet.rippletest.net:51234"

[timeout]
request_timeout_millis = 3000
backoff_max_elapsed_time_seconds = 300

[logger]
level = "DEBUG"
file = "logs/xrp_indexer.log"
console = true
